head.load("js/lib/jquery.js",
					"js/lib/cycle.js",
					"js/lib/jquery-ui.min.js",
					"js/lib/datepicker-localisation.min.js",
					"js/lib/jscrollpane.min.js",
					"js/lib/mousewheel.min.js",
					"js/lib/dial.min.js",
					"js/lib/select2.min.js",
					"js/common.js");
